# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: cosc4353group7_db
    image: mariadb:10
    restart: always
    environment:
      MARIADB_USER: 'app'
      MARIADB_PASSWORD: 'test_password'
      MARIADB_ROOT_PASSWORD: 'Test_Password754'
    networks:
      - backend
    ports:
      - "3306:3306"

  backend:
    container_name: cosc4353group7_backend
    image: cosc4353group7/fuelgo-backend
    build: 
      context: backend
      dockerfile: express.Dockerfile
    networks:
      - frontend
      - backend
    ports:
      - "3001:3001"

  frontend:
    image: cosc4353group7/fuelgo-frontend
    build: 
      context: frontend
      dockerfile: react.Dockerfile
    networks:
      - frontend
    ports:
      - "3000:3000"

networks:
  frontend:
  backend: